# version: "3.9"

# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile.backend   
#     ports:
#       - "8000:8000"
#     restart: unless-stopped
    

#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile.frontend
#       args:
#         REACT_APP_API_URL: http://localhost:8000  
#     depends_on:
#       - api
#     ports:
#       - "3000:80"
#     restart: unless-stopped

# version: "3.9"

# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile.backend   
#     ports:
#       - "8000:8000"
#     restart: unless-stopped
    

#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile.frontend
#       args:
#         REACT_APP_API_URL: http://localhost:8000  
#     depends_on:
#       - api
#     ports:
#       - "3000:80"
#     restart: unless-stopped



version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MLFLOW_TRACKING_URI=http://mlflow:3000
    volumes:
      - ./data:/app/data
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow_server
    ports:
      - "3000:3000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/app/artifacts
    volumes:
      - ./mlruns:/app/artifacts
    command: >
      mlflow server  --backend-store-uri sqlite:///mlflow.db  --default-artifact-root /app/artifacts  --host 0.0.0.0

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:80"
    depends_on:
      - backend